### ISSUE TITLE
Hol a script? 

### ISSUE THREAD

**Issue by jr-oszik** [Ekhion76/eco_crafting#1]
Szia ne haragudj de nem raktad fel.
Pedig atom ahogy kinéz.

**Comment by Ekhion76** [comment]
Szervusz,

a szkript majd tebex-en lesz elérhető, amint elkészül a kiadható verzió.
Több embernek mutogatom ötletek miatt, ezért van fent a leírása a githubon.

Örülök, hogy tetszik! :)

Üdv

jr-oszik ***@***.***> ezt írta (időpont: 2022. jún. 7., K,
13:22):

**Comment by jr-oszik** [comment]
Akkor várok köszönöm a választ 😁

Ekhion76 ***@***.***> ezt írta (időpont: 2022. jún. 7., K
13:41):
