### ISSUE TITLE
[QUESTION] Automatic points

### ISSUE THREAD

**Issue by amgmacht** [Ekhion76/eco_crafting#3]
How exactly can I switch off that people automatically get points every 5 minutes or automatically in general?

you should only get points if you process something?

Is there another way to get contact or support for the script?

**Comment by Ekhion76** [comment]
Hello, you can turn off the lab system in the config file here:

Config.systemMode = {
    profession = true, -- proficiency system on/off
    labor = true, -- if you turn off the lab, the profession system will automatically turn off
    money = true, -- money condition on/off
    chance = true -- chance system on/off
}

Discord is not yet fully built, but you can connect:
https://discord.gg/4arG5sEpqw
